### ISSUE TITLE
Ver vehiculo

### ISSUE THREAD

**Issue by matudelatower** [matudelatower/logiautos#11]
Cuando recién se crea un vehiculo, va a la pantalla de show.
Aparece habiltiado el boton de ver checklist de control interno.
<img width="1280" alt="captura de pantalla 2016-02-24 a las 9 02 50 a m" src="https://cloud.githubusercontent.com/assets/5694115/13284802/79cc0aa4-dad5-11e5-8bf6-bbfff17eda82.png">

y si hago click la pantalla queda bloqueada, hay un error de js.

<img width="1280" alt="captura de pantalla 2016-02-24 a las 9 02 56 a m" src="https://cloud.githubusercontent.com/assets/5694115/13284812/8e5e798e-dad5-11e5-98ba-4fb2ee1de618.png">

**Comment by johnnykatz** [comment]
terminado
