### ISSUE TITLE
agregar botonque permita realizar check-list de preentrega

### ISSUE THREAD

**Issue by johnnykatz** [matudelatower/logiautos#3]
Se debe agregar un botón en listado vehiculos recibidos (al estilo botón de actualizar remito en listado de vehiculos pendientes) que permita realizar el check list de preentrega.
En la pantalla del check list debe tener todos los check y al final debe permitir agregar daños (codificación interna que la voy a realizar hoy) al estilo de daños gm.
una vez que se guarde el check-list el vehículo pasa a estado "stock" (esto por el momento, tendríamos que agregar un estado mas donde diga en stock con daños o algo asi como cuando recibís con daños o ver algo parecido).

**Comment by matudelatower** [comment]
TODO: Pantalla de edición, sin que se guarde los checklist y a la seccion de daños internos se agregan los campos: solucionado (checkbox), numero de orden (text)
