### ISSUE TITLE
Reportes de autos vendidos por vendedor

### ISSUE THREAD

**Issue by johnnykatz** [matudelatower/logiautos#7]
Crear reporte de autos vendidos por un vendedor en un periodo. el mismo debe exportarse a excel y pdf.
Cabecera del reporte debe tener los datos del vendedor, sucursal a la que pertenece y periodo del reporte.
los datos a visualizar en el reporte son: vin,nombre vehiculo (ver columna "modelo" en listado de vehiculos), color y fecha de facturación de la unidad.

**Comment by matudelatower** [comment]
Falta definir encabezados y pie de paginas

**Comment by johnnykatz** [comment]
Se debe armar un layout base para reportes donde conste como header el logo seguido del nombre de la empresa. Un poco mas abajo en tamaño reducido el usuario que imprime y la fecha y hora.
En el cuerpo del reporte el titulo del reporte.
Y para este reporte en especial debe figurar como subtitulo, el vendedor y el periodo de fecha seleccionado.
en el footer debe aparecer el numero de pagina.
