### ISSUE TITLE
Control en codigo modelo

### ISSUE THREAD

**Issue by johnnykatz** [matudelatower/logiautos#73]
Se debe controlar en abm, codigo modelo, que no se agreguen duplicados. se considera duplicado cuando la totalidad de sus campos se repiten:
 año:2015, version:5p+airbag, codigo:xs07
en caso de tener la misma version y codigo pero tener el año distinto ya no se considera suplicado. y asi con los demas campos.

**Comment by matudelatower** [comment]
En que abm?
