### ISSUE TITLE
Agregar pregunta a la encuesta de alerta temprana

### ISSUE THREAD

**Issue by johnnykatz** [matudelatower/logiautos#83]
¿Autoriza a Gonzalez Automoviles S.A. a publicar  las imágenes capturadas al momento de la entrega de su Chevrolet 0 KM, a las redes sociales y página oficial del concesionario?
opciones:SI NO
Esta pregunta debe ser la ultima y debe estar resaltada de alguna manera, podria ser remarcada con lineas de puntos o como te parezca.

**Comment by matudelatower** [comment]
Se debe crear la pregunta en:
- /web/app_dev.php/cuestionario/encuesta_pregunta/new

y asignar opciones en: 

- web/app_dev.php/cuestionario/encuesta_opcion_respuesta/new

adjunto mail, con sql script por las dudas
